app:
  name: "development-app"
  version: "2.1.0"
  environment: "development"
  debug: true

server:
  host: "localhost"
  port: 8080
  read_timeout: "60s"
  write_timeout: "60s"
  idle_timeout: "120s"

database:
  url: "postgres://dev:dev@localhost:5432/dev_db"
  max_connections: 5
  min_connections: 1
  connection_timeout: "30s"
  query_timeout: "30s"
  ssl_mode: "disable"

logging:
  level: "debug"
  format: "text"
  output: "stdout"
  filename: ""
  max_size: 10
  max_age: 1
  compress: false

features:
  enable_metrics: false
  enable_cors: true
  enable_cache: false
  enable_rate_limit: false

services:
  redis:
    url: "redis://localhost:6379/1"
    timeout: "10s"
    pool_size: 5
  cache:
    ttl: "1m"
    max_size: 100
    strategy: "fifo"

security:
  jwt_secret: "dev-jwt-secret-key-for-development-only"
  session_secret: "dev-session-secret-key-for-development-only"
  token_expiry: "1h"
  bcrypt_cost: 4
